### ISSUE TITLE
toolbar bitmap failed to load

### ISSUE THREAD

**Issue by MikeHart66** [kfprimm/blitz3d-ng#1]
On startup, I get this error:

toolbar bitmap failed to load

**Comment by kfprimm** [comment]
Hey @MikeHart66, you can download a new build with this patch [here](https://github.com/kfprimm/blitz3d-ng/releases/download/v2.0.0-alpha.002/blitz3d_ng_v200-alpha.002.zip). Let me know what you find.

I noticed one strange issue. I downloaded the zip & started up the IDE. The "Samples" & "Geometricks Models" link don't open the file prompts. Strangely, the IDE in my build folder works find. It may be some weirdness with Windows security.

So, give it a shot & let me know what you find.

Thanks!

**Comment by MikeHart66** [comment]
Thank you, it works now with the newest version.
