### ISSUE TITLE
Can't build Blitz3D NG

### ISSUE THREAD

**Issue by MikeHart66** [kfprimm/blitz3d-ng#4]
I forked your repository. I installed VS 2015 community and DX10 SDK. I got premake5. 
Placed it inside the forked directory. On the command line I typed

> premake5 vs2015 && devenv build\blitz3d.sln /build release

Got an error that it can't find **devenv**. 

And so it doesn't build. Any suggestions?

**Comment by kfprimm** [comment]
You should have to install DirectX, it should already be installed.

Run the command in the developer prompt. Start -> Visual Studio 2015 -> Developer Command Prompt for VS2015

**Comment by MikeHart66** [comment]
Where does Premake5 have to be placed?

**Comment by kfprimm** [comment]
Anywhere in the PATH. You can drop into the root of the project folder, or `C:\Windows\System32`.

**Comment by MikeHart66** [comment]
Ok, I dropped it into windows/system32.
I open up the dev console like you said. So I am in the visual studio folder. There I type what I wrote above.
Tells me that it can't find premake.lua.

**Comment by kfprimm** [comment]
Sorry! Updated the README again. You need to type `cd blitz3d-ng` to jump into project folder.

Also, the default directory opens up to the VS folder in `Program Files`. You might want to jump to your Documents or Desktop & do it from there (`cd C:\Users\Mike\Desktop`, or whatever.)

**Comment by MikeHart66** [comment]
Ok, did that . Back to square one. Unknow command **devenv** or missing

**Comment by kfprimm** [comment]
Are you 100% sure you're in the "Develper Command Prompt?" Can you screenshot it for me?

**Comment by MikeHart66** [comment]
Ok, sorry. I thought it was only a command prompt. I went through the developmer console and now it doesn't complain about devenv anymore.
But it turns out now that my VS2015 installation has something missing. I will get back whne I fix this.
Thank you for the help so far.

**Comment by kfprimm** [comment]
No trouble! I appreciate your wanting to try things out.

It's probably the MFC stuff. Run the VS install again, click "Custom Install" or whatever it's called, & make sure MFC is checked. It may be under a legacy dropdown.

If you don't mind, can you write down the particulars so we can add it to the README?

**Comment by MikeHart66** [comment]
yes I will.

**Comment by MikeHart66** [comment]
Ok, got it almost ot compile. Here is the output. A few errors regarding a macro definition.

[test.txt](https://github.com/kfprimm/blitz3d-ng/files/643400/test.txt)

**Comment by kfprimm** [comment]
Can't understand all that German. :)

Seriously though, I forgot to commit the update to freeimage. Pull down & try again.

**Comment by kfprimm** [comment]
Almost there, I promise!

**Comment by MikeHart66** [comment]
Good morning. Thanks i will check it in a few hours. Need to help the wife.

**Comment by MikeHart66** [comment]
I couldn't resist. Still errors. Sorry for my german attachment. Search for ERROR inside the text file. It is about a redefinition of a macro  mostlikely regarding freeimage.

>  Macro definition of snprintf conflicts with Standard Library function declaration

[test.txt](https://github.com/kfprimm/blitz3d-ng/files/643674/test.txt)

**Comment by kfprimm** [comment]
Jump into freeimage317 and run "git log --oneline." There should be a commit from me referring to VS2015. If not, run "git pull origin master."

I like the enthusiasm. Sorry for the delay! Darn timezone difference!

**Comment by kfprimm** [comment]
If the directory is blank, you didn't add the "--recursive" flag when you cloned the repo. In that case run "git submodule init --update."

Alternatively, just delete the while repo and clone it again. :)

**Comment by MikeHart66** [comment]
Ok, before I just cloned it via the web interface and then used the gui app.

With the shell instructions it works. :-) Thanks for the help. I can compile now!
